from abc import ABC, abstractmethod
import pandas as pd
from portfolio_test.portfolio_manager import PortfolioManager
from portfolio_test.forge_data import DataForge

class BaseStrategy(ABC):
    """
    Abstract Base Class for all trading strategies.
    
    Any strategy must implement the `execute` method, taking in the pre-built 
    DataForge DataFrame and the PortfolioManager instance.
    """
    
    @property
    @abstractmethod
    def name(self) -> str:
        """Return the name of the strategy."""
        pass

    @abstractmethod
    def prepare_data(self, data: pd.DataFrame) -> pd.DataFrame:
        """
        Calculates all indicators and signals needed for the strategy.
        Should return the DataFrame with added signal columns.
        """
        pass

    @abstractmethod
    def execute(self, data: pd.DataFrame, pm: PortfolioManager):
        """
        Iterates over the data and executes BUY/SELL signals using the PortfolioManager.
        
        :param data: The pandas DataFrame generated by `prepare_data` containing indicators and prices.
        :param pm: The PortfolioManager instance to record transactions.
        """
        pass
